Repository Flipez/rocket-lang, pull requests merged in 2022-11, with the labels that each got.

#142 [object/error] Add ability to rescue errors and introduce `begin/rescue/end`
  ast/ast_test.go
  ast/begin.go
  ast/block.go
  ast/rescue.go
  docs/docs/literals/error.md
  docs/generate.go
  evaluator/block.go
  evaluator/evaluator.go
  evaluator/evaluator_test.go
  object/error.go
  parser/begin.go
  parser/block.go
  parser/parser.go
  token/token.go
Labels: enhancement

#143 [object/funtion] Missing name to use when inspect
  evaluator/evaluator.go
  object/function.go
Labels: bug

#144 [docs] Update documentation
  docs/components/GetStarted.tsx
  docs/components/Highlights.js
  docs/components/Highlights.module.css
  docs/components/get-started.module.css
  docs/docs/install.md
  docs/package.json
  docs/src/css/custom.css
  docs/yarn.lock
Labels: documentation, no-changelog

#145 [object/error] Add `raise()` builtin
  docs/docs/literals/error.md
  docs/generate.go
  evaluator/evaluator_test.go
  stdlib/raise.go
  stdlib/std.go
Labels: enhancement

#146 [release] Release 0.20.0
  CHANGELOG.md
  docs/docusaurus.config.js
  docs/versioned_docs/version-v0.20.0/builtins/HTTP.md
  docs/versioned_docs/version-v0.20.0/builtins/IO.md
  docs/versioned_docs/version-v0.20.0/builtins/JSON.md
  docs/versioned_docs/version-v0.20.0/builtins/Math.md
  docs/versioned_docs/version-v0.20.0/builtins/OS.md
  docs/versioned_docs/version-v0.20.0/builtins/Time.md
  docs/versioned_docs/version-v0.20.0/builtins/_category_.yml
  docs/versioned_docs/version-v0.20.0/control_expressions/_category_.yml
  docs/versioned_docs/version-v0.20.0/control_expressions/foreach.md
  docs/versioned_docs/version-v0.20.0/control_expressions/if.md
  docs/versioned_docs/version-v0.20.0/control_expressions/while.md
  docs/versioned_docs/version-v0.20.0/index.md
  docs/versioned_docs/version-v0.20.0/install.md
  docs/versioned_docs/version-v0.20.0/language/_category_.yml
  docs/versioned_docs/version-v0.20.0/language/modules.md
  docs/versioned_docs/version-v0.20.0/language/operators.md
  docs/versioned_docs/version-v0.20.0/literals/_category_.yml
  docs/versioned_docs/version-v0.20.0/literals/array.md
  docs/versioned_docs/version-v0.20.0/literals/boolean.md
  docs/versioned_docs/version-v0.20.0/literals/error.md
  docs/versioned_docs/version-v0.20.0/literals/file.md
  docs/versioned_docs/version-v0.20.0/literals/float.md
  docs/versioned_docs/version-v0.20.0/literals/hash.md
  docs/versioned_docs/version-v0.20.0/literals/http.md
  docs/versioned_docs/version-v0.20.0/literals/integer.md
  docs/versioned_docs/version-v0.20.0/literals/nil.md
  docs/versioned_docs/version-v0.20.0/literals/string.md
  docs/versioned_docs/version-v0.20.0/specification/_category_.yml
  docs/versioned_docs/version-v0.20.0/specification/builtins.md
  docs/versioned_docs/version-v0.20.0/specification/closures.md
  docs/versioned_docs/version-v0.20.0/specification/comments.md
  docs/versioned_docs/version-v0.20.0/specification/functions.md
  docs/versioned_docs/version-v0.20.0/specification/local_variables.md
  docs/versioned_sidebars/version-v0.20.0-sidebars.json
  docs/versions.json
Labels: no-changelog

#147 [object/string] Fix `.find()` and `.count()` argument validation to only accept STRING
  docs/docs/literals/string.md
  object/string.go
Labels: bug

#148 [object/string] Add support for HASH and ARRAY to `.format()`
  go.mod
  go.sum
  object/object.go
  object/object_test.go
  object/string.go
Labels: enhancement

#150 [release/goreleaser] Add tag to archive filename
  .goreleaser.yml
Labels: no-changelog

#157 Examples aoc
  examples/aoc/2018/day1.rl
  examples/aoc/2018/day1.txt
  examples/aoc/2018/day2.rl
  examples/aoc/2018/day2.txt
  examples/aoc/2018/day3.rl
  examples/aoc/2018/day3.txt
  examples/aoc/2018/util.rl
  examples/aoc/2020/2020-1.rl
  examples/aoc/2020/2020-2.rl
  examples/aoc/2020/2020-3.rl
  examples/aoc/2020/day1.txt
  examples/aoc/2020/day2.txt
  examples/aoc/2020/day3.txt
  examples/aoc/2020/util.rl
Labels: no-changelog
