Repository Flipez/rocket-lang, pull requests merged in 2022-01, with the labels that each got.

#34 rewrite file.read() and file.lines()
  docs/content/en/docs/literals/file.md
  examples/aoc/2021/day-1/complete.rl
  examples/aoc/2021/day-2/complete.rl
  examples/aoc/2021/day-2/input
  examples/aoc/2021/day-2/input_example
  object/file.go
  object/file_test.go
Labels: bug

#36 rewrite file handle, adjust file.seek()
  docs/content/en/docs/literals/file.md
  evaluator/evaluator_test.go
  object/error.go
  object/file.go
  object/file_test.go
  stdlib/open.go
Labels: enhancement

#39 remove let
  ast/ast.go
  ast/ast_test.go
  docs/content/en/docs/control_expressions/foreach.md
  docs/content/en/docs/home.md
  docs/content/en/docs/literals/boolean.md
  docs/content/en/docs/literals/hash.md
  docs/content/en/docs/literals/integer.md
  docs/content/en/docs/literals/string.md
  docs/content/en/docs/specification/closures.md
  docs/content/en/docs/specification/functions.md
  docs/content/en/docs/specification/local_variables.md
  docs/generate.go
  evaluator/evaluator.go
  evaluator/evaluator_test.go
  examples/aoc/2021/day-1/complete.rl
  lexer/lexer_test.go
  object/array_test.go
  object/hash_test.go
  object/string_test.go
  parser/parser.go
  parser/parser_test.go
  token/token.go
Labels: enhancement

#40 replace fn identifier with def
  docs/content/en/docs/specification/closures.md
  docs/content/en/docs/specification/comments.md
  docs/content/en/docs/specification/functions.md
  docs/content/en/docs/specification/modules.md
  evaluator/evaluator.go
  evaluator/evaluator_test.go
  fixtures/module.rl
  lexer/lexer_test.go
  object/file_test.go
  object/function.go
  object/function_test.go
  parser/parser_test.go
  token/token.go
Labels: enhancement

#43 implement type float
  ast/ast.go
  docs/content/en/docs/literals/float.md
  docs/content/en/docs/literals/integer.md
  docs/generate.go
  evaluator/evaluator.go
  lexer/lexer.go
  object/float.go
  object/float_test.go
  object/integer.go
  object/integer_test.go
  object/number_test.go
  object/object.go
  object/object_test.go
  parser/parser.go
  token/token.go
Labels: enhancement

#42 make curly braces optional
  ast/ast.go
  docs/content/en/docs/control_expressions/if.md
  docs/content/en/docs/home.md
  docs/content/en/docs/specification/functions.md
  evaluator/evaluator.go
  evaluator/evaluator_test.go
  examples/aoc/2021/day-2/complete.rl
  examples/misc/if.rl
  parser/parser.go
  token/token.go
Labels: enhancement

#47 clean up lexer
  lexer/lexer.go
  token/token.go
Labels: enhancement

#51 unify object creation with New methods
  evaluator/assign.go
  evaluator/evaluator.go
  evaluator/evaluator_test.go
  evaluator/foreach.go
  evaluator/hash.go
  evaluator/identifier.go
  evaluator/if.go
  evaluator/import.go
  evaluator/index.go
  evaluator/infix.go
  evaluator/module.go
  evaluator/object_call.go
  evaluator/prefix.go
  object/array.go
  object/array_test.go
  object/boolean.go
  object/boolean_test.go
  object/builtin.go
  object/environment.go
  object/error.go
  object/error_test.go
  object/file.go
  object/float.go
  object/float_test.go
  object/function.go
  object/hash.go
  object/hash_test.go
  object/integer.go
  object/integer_test.go
  object/module.go
  object/null.go
  object/null_test.go
  object/object.go
  object/object_test.go
  object/return_value.go
  object/return_value_test.go
  object/string.go
  object/string_test.go
  stdlib/exit.go
  stdlib/open.go
  stdlib/raise.go
  stdlib/std.go
Labels: enhancement

#49 improve tests
  ast/array.go
  ast/assign.go
  ast/ast.go
  ast/block.go
  ast/boolean.go
  ast/call.go
  ast/expression_statement.go
  ast/float.go
  ast/foreach.go
  ast/function.go
  ast/hash.go
  ast/identifier.go
  ast/if.go
  ast/import.go
  ast/index.go
  ast/infix.go
  ast/integer.go
  ast/object_call.go
  ast/prefix.go
  ast/return.go
  ast/string.go
  evaluator/evaluator_test.go
  object/array.go
  object/array_test.go
  object/boolean_test.go
  object/builtin_test.go
  object/file.go
  object/file_test.go
  object/hash.go
  object/hash_test.go
  object/object.go
  object/object_test.go
  object/string.go
  object/string_test.go
  token/token_test.go
  utilities/utilities.go
Labels: enhancement

#61 fix comments
  lexer/lexer.go
Labels: bug

#55 examples: Update aoc/2015/day1 to 0.14.1
  examples/aoc/2015/day1.input
  examples/aoc/2015/day1.rl
Labels: documentation

#62 Foreach error abort
  docs/content/docs/literals/float.md
  docs/content/docs/literals/integer.md
  docs/content/docs/literals/null.md
  evaluator/foreach.go
  examples/aoc/2021/day-1/complete.rl
  examples/misc/foreach-error.rl
  object/float.go
  object/float_test.go
  object/integer.go
  object/integer_test.go
  object/null.go
  object/null_test.go
Labels: bug, enhancement

#57 add cli flags
  docs/content/_index.md
  go.mod
  go.sum
  main.go
  repl/repl.go
Labels: enhancement

#56 Improve Error Messages
  README.md
  evaluator/evaluator_test.go
  evaluator/object_call.go
  lexer/lexer.go
  object/array_test.go
  object/boolean_test.go
  object/builtin_test.go
  object/error_test.go
  object/file_test.go
  object/float_test.go
  object/function_test.go
  object/hash_test.go
  object/integer_test.go
  object/null_test.go
  object/string_test.go
  parser/assign.go
  parser/expression.go
  parser/float.go
  parser/foreach.go
  parser/integer.go
  parser/parser.go
  token/token.go
  token/token_test.go
Labels: enhancement
