Repository Flipez/rocket-lang, pull requests merged in 2022-02, with the labels that each got.

#65 Improve Infix operator
  evaluator/infix.go
  object/string_test.go
Labels: enhancement

#66 object/integer: satisfy iterable interface
  docs/content/docs/control_expressions/foreach.md
  object/integer.go
  object/integer_test.go
  parser/foreach.go
  parser/parser_test.go
Labels: enhancement

#73 add ternary
  ast/ternary.go
  evaluator/evaluator.go
  evaluator/evaluator_test.go
  evaluator/ternary.go
  lexer/lexer.go
  parser/parser.go
  parser/ternary.go
  token/token.go
Labels: enhancement

#76 add missing quotation mark in string documentation
  docs/content/docs/literals/string.md
  docs/generate.go
Labels: documentation

#77 add ast tests
  ast/ast_test.go
  ast/boolean.go
  ast/float.go
  ast/foreach.go
  ast/if.go
  ast/integer.go
  ast/return.go
  ast/string.go
Labels: enhancement

#75 Implement while loop
  ast/ast_test.go
  ast/while.go
  docs/content/docs/control_expressions/while.md
  evaluator/evaluator.go
  evaluator/foreach.go
  evaluator/while.go
  main_test.go
  object/environment.go
  object/environment_test.go
  parser/parser.go
  parser/while.go
  tests/while.expected
  tests/while.rl
  token/token.go
Labels: enhancement

#80 Fix indexable object types
  ast/assign.go
  ast/index.go
  docs/content/docs/literals/array.md
  docs/content/docs/literals/hash.md
  docs/content/docs/literals/string.md
  docs/generate.go
  evaluator/assign.go
  evaluator/assign_test.go
  evaluator/evaluator.go
  evaluator/evaluator_test.go
  evaluator/index.go
  evaluator/index_test.go
  parser/assign.go
  parser/expression.go
  parser/index.go
  tests/indexables.expected
  tests/indexables.rl
Labels: bug
