Repository Flipez/rocket-lang, pull requests merged in 2022-12, with the labels that each got.

#162 object/hash: add get method with default if key not exists
  docs/docs/literals/hash.md
  docs/literals/hash.yml
  object/hash.go
  object/hash_test.go
Labels: enhancement

#167 update docs
  docs/docusaurus.config.js
  docs/versioned_docs/version-v0.21.0/builtins/HTTP.md
  docs/versioned_docs/version-v0.21.0/builtins/IO.md
  docs/versioned_docs/version-v0.21.0/builtins/JSON.md
  docs/versioned_docs/version-v0.21.0/builtins/Math.md
  docs/versioned_docs/version-v0.21.0/builtins/OS.md
  docs/versioned_docs/version-v0.21.0/builtins/Time.md
  docs/versioned_docs/version-v0.21.0/builtins/_category_.yml
  docs/versioned_docs/version-v0.21.0/control_expressions/_category_.yml
  docs/versioned_docs/version-v0.21.0/control_expressions/foreach.md
  docs/versioned_docs/version-v0.21.0/control_expressions/if.md
  docs/versioned_docs/version-v0.21.0/control_expressions/while.md
  docs/versioned_docs/version-v0.21.0/index.md
  docs/versioned_docs/version-v0.21.0/install.md
  docs/versioned_docs/version-v0.21.0/language/_category_.yml
  docs/versioned_docs/version-v0.21.0/language/modules.md
  docs/versioned_docs/version-v0.21.0/language/operators.md
  docs/versioned_docs/version-v0.21.0/literals/_category_.yml
  docs/versioned_docs/version-v0.21.0/literals/array.md
  docs/versioned_docs/version-v0.21.0/literals/boolean.md
  docs/versioned_docs/version-v0.21.0/literals/error.md
  docs/versioned_docs/version-v0.21.0/literals/file.md
  docs/versioned_docs/version-v0.21.0/literals/float.md
  docs/versioned_docs/version-v0.21.0/literals/hash.md
  docs/versioned_docs/version-v0.21.0/literals/http.md
  docs/versioned_docs/version-v0.21.0/literals/integer.md
  docs/versioned_docs/version-v0.21.0/literals/nil.md
  docs/versioned_docs/version-v0.21.0/literals/string.md
  docs/versioned_docs/version-v0.21.0/specification/_category_.yml
  docs/versioned_docs/version-v0.21.0/specification/builtins.md
  docs/versioned_docs/version-v0.21.0/specification/closures.md
  docs/versioned_docs/version-v0.21.0/specification/comments.md
  docs/versioned_docs/version-v0.21.0/specification/functions.md
  docs/versioned_docs/version-v0.21.0/specification/local_variables.md
  docs/versioned_sidebars/version-v0.21.0-sidebars.json
  docs/versions.json
Labels: documentation, no-changelog

#173 [errorhandling] Fix line position, add `file:line:pos` to multiple error messages
  ast/ast_test.go
  ast/object_call.go
  evaluator/evaluator_test.go
  evaluator/foreach.go
  evaluator/identifier.go
  evaluator/import.go
  evaluator/module.go
  evaluator/object_call.go
  lexer/lexer.go
  lexer/lexer_test.go
  main.go
  main_test.go
  object/array_test.go
  object/boolean_test.go
  object/builtin_test.go
  object/error_test.go
  object/file_test.go
  object/float_test.go
  object/function_test.go
  object/hash_test.go
  object/http_test.go
  object/integer_test.go
  object/json_test.go
  object/nil_test.go
  object/object_test.go
  object/string_test.go
  parser/method_call.go
  parser/parser.go
  parser/parser_test.go
  repl/repl.go
  token/token.go
Labels: bug, enhancement

#168 [evaluator/while]: Add support for `break`
  docs/docs/control_expressions/while.md
  evaluator/while.go
  tests/while.expected
  tests/while.rl
Labels: bug

#175 [object] Refactor type conversion and rename methods
  docs/components/Highlights.js
  docs/docs/control_expressions/foreach.md
  docs/docs/index.md
  docs/docs/literals/array.md
  docs/docs/literals/boolean.md
  docs/docs/literals/error.md
  docs/docs/literals/file.md
  docs/docs/literals/float.md
  docs/docs/literals/hash.md
  docs/docs/literals/http.md
  docs/docs/literals/integer.md
  docs/docs/literals/nil.md
  docs/docs/literals/string.md
  docs/literals/boolean.yml
  docs/literals/float.yml
  docs/literals/integer.yml
  docs/literals/nil.yml
  docs/literals/object.yml
  docs/literals/string.yml
  evaluator/infix.go
  examples/aoc/2015/day1.rl
  examples/aoc/2018/day1.rl
  examples/aoc/2018/day3.rl
  examples/aoc/2018/util.rl
  examples/aoc/2020/2020-1.rl
  examples/aoc/2020/2020-2.rl
  examples/aoc/2020/util.rl
  examples/aoc/2021/day-1/complete.rl
  examples/aoc/2021/day-2/complete.rl
  object/array_test.go
  object/boolean.go
  object/boolean_test.go
  object/file_test.go
  object/float.go
  object/float_test.go
  object/hash_test.go
  object/http_test.go
  object/integer.go
  object/integer_test.go
  object/nil.go
  object/nil_test.go
  object/object.go
  object/string.go
  object/string_test.go
Labels: enhancement

#176 [foreach/while] Document return value
  docs/docs/control_expressions/foreach.md
  docs/docs/control_expressions/while.md
Labels: documentation, no-changelog

#177 [object/array] Add ability to `.join()` elements
  docs/docs/literals/array.md
  object/array.go
  object/array_test.go
Labels: enhancement

#178 [object/array] Add ability to `.sum()` elements
  docs/docs/literals/array.md
  object/array.go
  object/array_test.go
Labels: enhancement

#179 [object/array] Rename `.yeet()` and `.yoink()` to `.pop()` and `.push()`
  docs/components/Highlights.js
  docs/docs/control_expressions/foreach.md
  docs/docs/index.md
  docs/docs/literals/array.md
  docs/literals/array.yml
  examples/aoc/2018/day1.rl
  examples/aoc/2018/day3.rl
  examples/aoc/2018/util.rl
  examples/aoc/2020/2020-1.rl
  examples/aoc/2020/util.rl
  examples/aoc/2021/day-1/complete.rl
  object/array.go
  object/array_test.go
  object/hash_test.go
  object/string_test.go
Labels: enhancement

#180 [core] Refactor `int64` to `int` where possible
  ast/integer.go
  docs/docs/literals/array.md
  evaluator/assign.go
  evaluator/evaluator_test.go
  evaluator/index.go
  evaluator/infix.go
  object/array.go
  object/file.go
  object/float.go
  object/http.go
  object/integer.go
  object/integer_test.go
  object/object.go
  object/object_test.go
  object/string.go
  parser/integer.go
  parser/parser_test.go
  stdlib/time.go
Labels: enhancement, no-changelog
